### ISSUE TITLE
service.doLogin() return false. Unable to login to any account

### ISSUE THREAD

**Issue by dimti** [nnhiti/google-alert-api#10]
service = new GAService("myeuser@mydomain.ru", "pass");

            service.doLogin(); // - That return is boolean "false"

I tried with correct access credentionals with two another accounts. With browser - auth ok. With Java application - fail.

Please. Tell me. What make i wrong? May be, google change safe politics / captcha / change API version?

approximately - google-aler-api do not work start with 16 february 2016. But may be is permanently bug and now i cannot login...

**Comment by mrtreeGER** [comment]
Hi, i've got the same problem like dimti. Do you have any idea why this happens?

**Comment by ytwig** [comment]
I've fixed this issue in a new repository (as this one didn't have the source code).
You can find it here https://github.com/ytwig/google-alerts/

**Comment by nnhiti** [comment]
Thanks @dimti and @mrtreeGER for reporting the issue:

The issue fixed already. Please download the latest version and let me know if you need more information

**Comment by nnhiti** [comment]
@ytwig Please do not de-compile the jar lib, I will announce the code later as I'm not ready yet.

Thanks

**Comment by mrtreeGER** [comment]
Thank you very much, it works fine !
