### ISSUE TITLE
Doc usage - alert.setResultType - deprecated and not exists method

### ISSUE THREAD

**Issue by dimti** [nnhiti/google-alert-api#6]
Hi

In your doc says (Create alert section):
```
alert.setResultType(ResultType.EVERYTHING);
```

But that method not exists

I replace that method to:
```
String[] sources = new String[]{Sources.AUTOMATIC};
alert.setSources(sources);
```

I right?

**Comment by nnhiti** [comment]
Yes, you''re correct. 

Sorry, I did not update document here

Thanks
