### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by goodluckluke** [nnhiti/google-alert-api#7]
Hi, 

First of all, thanks for the great work, which fits well with what I want to do  :).

However, I do have problem with logging in. I got the error message as shown below. Is this a problem related to my internet setup? BTW, I have no problem logging into the account using a web browser. 
![google_alerts](https://cloud.githubusercontent.com/assets/6701634/8517254/997a719c-23f1-11e5-99ce-957b7dbe5085.png)
 
I really appreciate your help. Thanks a lot!

Best,
Luke

**Comment by nnhiti** [comment]
Hi Luke,

Yeah, I think your network have some issues, so please ensure that you can
connect to the internet and also can login to google website.

You can ping google.com to see the response from google or not.

Regards,
Ha Nguyen

**Comment by goodluckluke** [comment]
Hi Ha Nguyen,

I have no problem accessing those websites from a browser, but a ping test gave "Request timed out". In this case, is it still possible to use the package (a proxy, maybe?)? Thanks a lot!

Best,
Luke

**Comment by nnhiti** [comment]
Hi Luke,

Yeah, I think you should check your network, you should be able to ping the
google page and get the response.

Thanks and Regards,
Ha Nguyen

**Comment by goodluckluke** [comment]
Thanks a lot, Ha Nguyen.

I think I have located the problem. I am using corporate network which use a proxy to connect to the network. Thus I can browse the websites but cannot ping them. I am wondering if it is possible to integrate proxy setup into this api or this should be done in application level using interfaces such as System.proxyHost and System.proxyPort?. 

I am sorry if my question is too trivial. I am a newbie to Java (started a couple of days ago).

thanks again for your help.

Best,
Luke

**Comment by nnhiti** [comment]
Hi Luke,

Your suggestion is very useful for people who using proxy. So I send to you
the latest jar that supporting the proxy, please help me test it on you
network if you have free time. If it is working fine or any issues please
let me know.

I package the jar using java 1.7, if you're using 1.6 please let me know.

Note: google doesn't allow attach the jar file so please change the
extension of the attached file from "raj" to "jar" and using it.

Thanks and Regards,
Ha Nguyen,

**Comment by goodluckluke** [comment]
Hi Ha Nguyen,

I am very glad to test it out. But I am missing your email. Could you please send it again to yiwangalerts1576@gmail.com? And if possible, please send both the 1.6 and 1.7 version since I have Java 1.6 on my Linux and Java 1.7 on my windows,

Thanks a lot!
Best,
Luke

**Comment by goodluckluke** [comment]
Hi Ha Nguyen,

I haven't got the time to do extensive testing. But the proxy functionality worked well for me in a preliminary test.  :+1: Thanks a lot for the great work!

Best,
Luke

**Comment by IrtazaS** [comment]
Hi Nguyen,

i am using a proxy in a corporate network aswell. The API isn't working for me. Can you send me the jar supporting proxy? I would be very thankful.

Regards
Syed

**Comment by nnhiti** [comment]
The jar you're using also support the proxy, you can pass the proxy server via the params when you create the service instance

E.g: GAService service = new GAService(email, pass, proxy);
   Or GAService service = new GAService(email, pass, proxy, port);
