### ISSUE TITLE
You should provide the source code

### ISSUE THREAD

**Issue by jamescarr** [nnhiti/google-alert-api#8]
It is incredibly daft to push a jar onto github.

**Comment by nnhiti** [comment]
Sorry my friend, I cannot publish my code onto githup until now as these codes have not finalized yet, I have to get feedbacks and fix issues from the user; the codes are also very messy.

**Comment by ytwig** [comment]
I've decompiled the code and fixed an issue with login.
You can find it here https://github.com/ytwig/google-alerts/

**Comment by nnhiti** [comment]
@ytwig Please do not de-compile the jar lib, I will announce the code later as I'm not ready yet.

Thanks
